//
// Created by daniele on 14/10/19.
//

#ifndef PDS_COLLABORATIVETEXTEDITOR_2020_CHARACTER_H
#define PDS_COLLABORATIVETEXTEDITOR_2020_CHARACTER_H


class character {

};


#endif //PDS_COLLABORATIVETEXTEDITOR_2020_CHARACTER_H
