//
// Created by daniele on 14/10/19.
//

#ifndef PDS_COLLABORATIVETEXTEDITOR_2020_MESSAGE_H
#define PDS_COLLABORATIVETEXTEDITOR_2020_MESSAGE_H


class message {

};


#endif //PDS_COLLABORATIVETEXTEDITOR_2020_MESSAGE_H
