//
// Created by daniele on 14/10/19.
//

#ifndef PDS_COLLABORATIVETEXTEDITOR_2020_NETWORK_MANAGER_H
#define PDS_COLLABORATIVETEXTEDITOR_2020_NETWORK_MANAGER_H


class network_manager {

};


#endif //PDS_COLLABORATIVETEXTEDITOR_2020_NETWORK_MANAGER_H
